### ISSUE TITLE
xanalyzer

### ISSUE THREAD

**Issue by zhansugirov** [qux-bbb/xanalyzer#3]
Hello! 
Trying to install your scanner. Can you help me with it? Is any video instruction? 
Which OS you use?

**Comment by qux-bbb** [comment]
Sorry, no video instruction.  
I use win10, win11 and ubuntu22.  
What have you tried and encountered? Do you have log or error info?

**Comment by zhansugirov** [comment]
Hello!
Thank you for answering my questions
I use Ubuntu 22 in the vmware esxi server and when starting scripts I get a
lot of errors, most of the requirements are not installed. And also
docker-compose file does not up.
I have a task in my work to up opensource multiscanner for company users. I
already install cuckoo sandbox, but with multiscanner I have problem.
I also tried to install into venv, but get errors. Dont you have any guide
to install step by step?:) I will be very appreciate

ср, 15 февр. 2023 г. в 19:58, qux-bbb ***@***.***>:

**Comment by qux-bbb** [comment]
Sorry. I haven't used multiscanner, I just referred to some logic.  
If you have problem about xanalyzer, I can help you. You can read english README https://github.com/qux-bbb/xanalyzer/blob/master/README-en.md

**Comment by zhansugirov** [comment]
I got an error when trying to check the url or file. Maybe I should
preinstall some dependencies? And is there a web interface for this
scanner?

пн, 20 февр. 2023 г. в 19:25, qux-bbb ***@***.***>:

**Comment by qux-bbb** [comment]
Do you use method 2 to install?  
You can try method 1.  
There should be a problem with method 2, and I will try to fix it.  
If you still cannot install it, please tell me what you do and what info you see.  
The xanalyzer does not have web interface. It is just a simple tool, and it can only get some simple information.

**Comment by zhansugirov** [comment]
Oh ok, got you. I needed with web interface for users who will upload files. Anyway thank you for helping:)

**Comment by qux-bbb** [comment]
Sorry I can not help you for multiscanner.  
And Cuckoo is no longer maintained. I think it is better to use CAPEv2 https://github.com/kevoreilly/CAPEv2
